let perfilesUsuarios=[];
let permisosUsuarios={};
const clientUsuarios=window.PMOAuth?.client;
const MODULOS=[
  {code:'selfservice',name:'Mis solicitudes',desc:'Alta y seguimiento de solicitudes propias',icon:'file-plus-2'},
  {code:'matriz',name:'Matriz',desc:'Gestión operativa del portafolio',icon:'list-checks'},
  {code:'rqm',name:'Control RQM',desc:'Revisión, folios y aprobación de solicitudes',icon:'clipboard-list'},
  {code:'dashboard',name:'Dashboard',desc:'Indicadores ejecutivos',icon:'layout-dashboard'},
  {code:'seguimiento',name:'Seguimiento',desc:'Roadmap, gráficas y reportes',icon:'route'},
  {code:'importar',name:'Importar',desc:'Carga masiva de la matriz',icon:'file-up'},
  {code:'catalogos',name:'Catálogos',desc:'Configuración funcional',icon:'settings-2'},
  {code:'usuarios',name:'Usuarios',desc:'Cuentas, roles y permisos',icon:'users-round'}
];
function eu(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));}
function rolBadge(rol){const c={administrador:'bg-violet-50 text-violet-700',pmo:'bg-blue-50 text-blue-700',direccion:'bg-amber-50 text-amber-700',usuario:'bg-slate-100 text-slate-700'}[rol]||'bg-slate-100';return `<span class="px-3 py-1 rounded-full text-xs font-black ${c}">${eu(window.PMOAuth.roleLabel(rol))}</span>`;}
function nivelBadge(level){const c={none:'bg-rose-50 text-rose-700',read:'bg-amber-50 text-amber-700',manage:'bg-emerald-50 text-emerald-700'}[level]||'bg-slate-100';return `<span class="px-2.5 py-1 rounded-full text-[11px] font-black ${c}">${eu(window.PMOAuth.levelLabel(level))}</span>`;}
function plantillaRol(rol){return window.PMOAuth.defaultsForRole(rol);}
function permisosDe(id,rol){return permisosUsuarios[id]||plantillaRol(rol);}
async function cargarPerfiles(){
 const tbody=document.getElementById('tabla-usuarios');tbody.innerHTML='<tr><td colspan="6" class="p-10 text-center text-slate-400">Cargando perfiles y permisos...</td></tr>';
 const [{data,error},{data:access,error:accessError}]=await Promise.all([
  clientUsuarios.from('pmo_user_profiles').select('user_id,nombre,correo,rol,activo,area_id,created_at,updated_at').order('nombre'),
  clientUsuarios.from('pmo_user_module_access').select('user_id,module_code,access_level')
 ]);
 if(error){tbody.innerHTML=`<tr><td colspan="6" class="p-10 text-center text-rose-600">${eu(error.message)}</td></tr>`;return;}
 permisosUsuarios={};
 if(!accessError)(access||[]).forEach(x=>{(permisosUsuarios[x.user_id]??={})[x.module_code]=x.access_level});
 perfilesUsuarios=data||[];renderPerfiles();renderKPIs();
}
function renderKPIs(){if(!document.getElementById('kpis-usuarios'))return;const items=[['TOTAL',perfilesUsuarios.length,'users'],['USUARIOS',perfilesUsuarios.filter(x=>x.rol==='usuario').length,'user'],['PMO / DIRECCIÓN',perfilesUsuarios.filter(x=>['pmo','direccion'].includes(x.rol)).length,'briefcase-business'],['ACTIVOS',perfilesUsuarios.filter(x=>x.activo!==false).length,'badge-check']];document.getElementById('kpis-usuarios').innerHTML=items.map(x=>`<div class="card p-5 flex justify-between"><div><p class="text-xs font-black text-slate-400">${x[0]}</p><p class="text-3xl font-black text-slate-950 mt-2">${x[1]}</p></div><div class="w-11 h-11 rounded-2xl bg-blue-50 text-blue-600 grid place-items-center"><i data-lucide="${x[2]}" class="w-5 h-5"></i></div></div>`).join('');lucide.createIcons();}
function resumenPermisos(p){const perms=permisosDe(p.user_id,p.rol);const n=MODULOS.filter(m=>(perms[m.code]||'none')!=='none').length;return `<span class="font-black text-slate-800">${n}</span><span class="text-slate-400"> / ${MODULOS.length} módulos</span>`;}
function renderPerfiles(){const q=(document.getElementById('buscar-usuario').value||'').toLowerCase();const rows=perfilesUsuarios.filter(p=>(`${p.nombre||''} ${p.correo||''}`).toLowerCase().includes(q));document.getElementById('tabla-usuarios').innerHTML=rows.length?rows.map(p=>`<tr><td class="p-4 font-black text-slate-900">${eu(p.nombre||'Sin nombre')}</td><td class="p-4 text-slate-600">${eu(p.correo||'—')}</td><td class="p-4">${rolBadge(p.rol)}</td><td class="p-4 text-sm">${resumenPermisos(p)}</td><td class="p-4"><span class="inline-flex items-center gap-2 font-bold ${p.activo===false?'text-rose-600':'text-emerald-600'}"><span class="w-2.5 h-2.5 rounded-full ${p.activo===false?'bg-rose-500':'bg-emerald-500'}"></span>${p.activo===false?'Inactivo':'Activo'}</span></td><td class="p-4 text-right"><button onclick="abrirEditarUsuario('${p.user_id}')" class="px-4 py-2 rounded-xl border border-slate-200 font-black text-slate-700 inline-flex gap-2"><i data-lucide="pencil" class="w-4 h-4"></i>Editar</button></td></tr>`).join(''):'<tr><td colspan="6" class="p-10 text-center text-slate-400">No se encontraron perfiles.</td></tr>';lucide.createIcons();}
function permissionGrid(prefix,permissions){return MODULOS.map(m=>`<div class="permission-row"><div class="permission-copy"><span class="permission-icon"><i data-lucide="${m.icon}"></i></span><div><strong>${m.name}</strong><small>${m.desc}</small></div></div><select id="${prefix}-perm-${m.code}" class="field permission-select" data-module="${m.code}"><option value="none">Sin acceso</option><option value="read">Solo consulta</option><option value="manage">Gestión</option></select></div>`).join('');}
function setPermissionValues(prefix,perms){MODULOS.forEach(m=>{const el=document.getElementById(`${prefix}-perm-${m.code}`);if(el)el.value=perms[m.code]||'none'});}
function readPermissionValues(prefix){const out={};MODULOS.forEach(m=>out[m.code]=document.getElementById(`${prefix}-perm-${m.code}`)?.value||'none');return out;}
async function applyRoleTemplate(prefix,role,ask=false){if(ask&&!(await PMOConfirm('Se reemplazarán los niveles seleccionados por la plantilla recomendada del rol.',{title:'Aplicar plantilla de permisos',confirmText:'Sí, aplicar'})))return;setPermissionValues(prefix,plantillaRol(role));lucide.createIcons();}
function setEditStatus(text,type='info'){const el=document.getElementById('edit-user-status');if(!el)return;el.className=`status-note ${type}`;el.textContent=text;}
function abrirEditarUsuario(id){const p=perfilesUsuarios.find(x=>x.user_id===id);if(!p)return;document.getElementById('edit-user-id').value=p.user_id;document.getElementById('edit-nombre').value=p.nombre||'';document.getElementById('edit-correo').value=p.correo||'';document.getElementById('edit-password').value='';document.getElementById('edit-rol').value=p.rol||'usuario';document.getElementById('edit-activo').checked=p.activo!==false;document.getElementById('edit-permissions-grid').innerHTML=permissionGrid('edit',permisosDe(p.user_id,p.rol));setPermissionValues('edit',permisosDe(p.user_id,p.rol));setEditStatus('El rol carga una plantilla; puedes personalizar cada módulo. Deja la contraseña vacía para conservarla.','info');document.getElementById('modal-usuario').classList.remove('hidden');lucide.createIcons();}
function cerrarModalUsuario(){document.getElementById('modal-usuario').classList.add('hidden');}
async function guardarPerfil(e){e.preventDefault();const btn=document.getElementById('btn-guardar-usuario');const password=document.getElementById('edit-password').value;const payload={user_id:document.getElementById('edit-user-id').value,nombre:document.getElementById('edit-nombre').value.trim(),correo:document.getElementById('edit-correo').value.trim().toLowerCase(),rol:document.getElementById('edit-rol').value,activo:document.getElementById('edit-activo').checked,permissions:readPermissionValues('edit')};if(password)payload.password=password;if(password&&password.length<8){setEditStatus('La nueva contraseña debe tener al menos 8 caracteres.','error');return;}btn.disabled=true;btn.textContent='Guardando...';try{const{data,error}=await clientUsuarios.functions.invoke('admin-update-user',{body:payload});if(error)throw error;if(data?.error)throw new Error(data.error);setEditStatus('Usuario y permisos actualizados correctamente.','success');await cargarPerfiles();setTimeout(cerrarModalUsuario,800)}catch(err){console.error(err);let detalle=err?.message||String(err);try{if(err?.context instanceof Response){const body=await err.context.clone().json();detalle=body?.error||body?.message||detalle}}catch{}setEditStatus(`No se pudo actualizar: ${detalle}`,'error')}finally{btn.disabled=false;btn.textContent='Guardar cambios'}}
function abrirNuevoUsuario(){document.getElementById('form-nuevo-usuario').reset();document.getElementById('new-activo').checked=true;document.getElementById('new-permissions-grid').innerHTML=permissionGrid('new',plantillaRol('usuario'));setPermissionValues('new',plantillaRol('usuario'));setNuevoStatus('El rol propone una plantilla inicial; puedes personalizarla antes de crear la cuenta.','info');document.getElementById('modal-nuevo-usuario').classList.remove('hidden');lucide.createIcons();}
function cerrarNuevoUsuario(){document.getElementById('modal-nuevo-usuario').classList.add('hidden');}
function setNuevoStatus(text,type='info'){const el=document.getElementById('nuevo-user-status');el.className=`status-note ${type}`;el.textContent=text;}
async function crearUsuario(e){e.preventDefault();const btn=document.getElementById('btn-crear-usuario');btn.disabled=true;btn.innerHTML='<span class="animate-pulse">Creando...</span>';const payload={nombre:document.getElementById('new-nombre').value.trim(),correo:document.getElementById('new-correo').value.trim().toLowerCase(),rol:document.getElementById('new-rol').value,password:document.getElementById('new-password').value,activo:document.getElementById('new-activo').checked,permissions:readPermissionValues('new')};try{const{data,error}=await clientUsuarios.functions.invoke('admin-create-user',{body:payload});if(error)throw error;if(data?.error)throw new Error(data.error);setNuevoStatus('Usuario y permisos creados correctamente.','success');await cargarPerfiles();setTimeout(cerrarNuevoUsuario,900)}catch(err){console.error(err);let detalle=err?.message||String(err);try{if(err?.context instanceof Response){const body=await err.context.clone().json();detalle=body?.error||body?.message||detalle}}catch{}setNuevoStatus(`No se pudo crear: ${detalle}`,'error')}finally{btn.disabled=false;btn.innerHTML='<i data-lucide="user-plus" class="w-4 h-4"></i>Crear usuario';lucide.createIcons()}}
window.abrirNuevoUsuario=abrirNuevoUsuario;window.cerrarNuevoUsuario=cerrarNuevoUsuario;window.cargarPerfiles=cargarPerfiles;window.abrirEditarUsuario=abrirEditarUsuario;window.cerrarModalUsuario=cerrarModalUsuario;window.applyRoleTemplate=applyRoleTemplate;
window.addEventListener('DOMContentLoaded',async()=>{const auth=await window.PMOAuth.guardPage();if(!auth)return;document.getElementById('hero-usuarios').innerHTML=window.PMOLayout.renderExecutiveHero({pill:'Administración de accesos',title:'Usuarios, roles y permisos',subtitle:'Asigna a cada persona Sin acceso, Solo consulta o Gestión por módulo.'});document.getElementById('buscar-usuario').addEventListener('input',renderPerfiles);document.getElementById('form-usuario').addEventListener('submit',guardarPerfil);document.getElementById('form-nuevo-usuario').addEventListener('submit',crearUsuario);document.getElementById('edit-rol').addEventListener('change',e=>applyRoleTemplate('edit',e.target.value,true));document.getElementById('new-rol').addEventListener('change',e=>applyRoleTemplate('new',e.target.value,false));await cargarPerfiles();lucide.createIcons();});
